version: '3.9'
services:
  server:
    build:
      context: .
    ports:
      - "8000:3000"
    volumes:
      - ./app/src:/app/src
      - ./app/.env:/app/.env
    command: >
      sh -c "npm run build &&
             npm start"
    environment:
      DB_HOST:      postgres
      DB_NAME:      daniel_dev
      DB_USER:      daniel_dev
      DB_PASSWORD:  changeme
      DB_PORT:      5432
